services:
  app:
    container_name: app
    build:
      context: .
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
      - 5173:5173
    environment:
      - PG_HOST=postgres
      - REDIS_HOST=redis
    volumes:
      - .:/app:cached
      - node-modules:/app/node_modules
  postgres:
    container_name: postgres
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: portal
  redis:
    container_name: redis
    image: redis:6-alpine
    volumes:
      - redis-volume:/data
    ports:
      - 6379:6379

volumes:
  db-store:
  node-modules:
  redis-volume:
